apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nickpande/k8s-manifests   # ðŸ‘ˆ YOUR GIT REPO
    path: sonarqube                                      # ðŸ‘ˆ folder path
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml                                    # ðŸ‘ˆ file INSIDE repo

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
